//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_buscar_carrera_x_id.
        /// </summary>
        internal static string PABuscarCarreraXId {
            get {
                return ResourceManager.GetString("PABuscarCarreraXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_buscar_curso_x_codigo.
        /// </summary>
        internal static string PABuscarCursoXCodigo {
            get {
                return ResourceManager.GetString("PABuscarCursoXCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_buscar_curso_x_nombre.
        /// </summary>
        internal static string PABuscarCursoXNombre {
            get {
                return ResourceManager.GetString("PABuscarCursoXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_buscar_grupo_x_nombre.
        /// </summary>
        internal static string PABuscarGrupoXNombre {
            get {
                return ResourceManager.GetString("PABuscarGrupoXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_buscar_usuario_x_nombre.
        /// </summary>
        internal static string PABuscarUsuarioXNombre {
            get {
                return ResourceManager.GetString("PABuscarUsuarioXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_listar_carreras.
        /// </summary>
        internal static string PAListarCarreras {
            get {
                return ResourceManager.GetString("PAListarCarreras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_listar_grupos.
        /// </summary>
        internal static string PAListarGrupos {
            get {
                return ResourceManager.GetString("PAListarGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_listar_profesores.
        /// </summary>
        internal static string PAListarProfesores {
            get {
                return ResourceManager.GetString("PAListarProfesores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_Listar_Rol.
        /// </summary>
        internal static string PAListarRol {
            get {
                return ResourceManager.GetString("PAListarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_Listar_Usuarios.
        /// </summary>
        internal static string PAListarUsuarios {
            get {
                return ResourceManager.GetString("PAListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PA_listar_Usuarios_Cedula.
        /// </summary>
        internal static string PAlistarUsuariosCedula {
            get {
                return ResourceManager.GetString("PAlistarUsuariosCedula", resourceCulture);
            }
        }
    }
}
