//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_Buscar_Carrera_X_Nombre.
        /// </summary>
        internal static string PABuscarCarreraXNombre {
            get {
                return ResourceManager.GetString("PABuscarCarreraXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_buscar_curso_x_codigo.
        /// </summary>
        internal static string PABuscarCursoXCodigo {
            get {
                return ResourceManager.GetString("PABuscarCursoXCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_buscar_curso_x_nombre.
        /// </summary>
        internal static string PABuscarCursoXNombre {
            get {
                return ResourceManager.GetString("PABuscarCursoXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_buscar_grupo_x_nombre.
        /// </summary>
        internal static string PABuscarGrupoXNombre {
            get {
                return ResourceManager.GetString("PABuscarGrupoXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_buscar_usuario_x_nombre.
        /// </summary>
        internal static string PABuscarUsuarioXNombre {
            get {
                return ResourceManager.GetString("PABuscarUsuarioXNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_listar_carreras.
        /// </summary>
        internal static string PAListarCarreras {
            get {
                return ResourceManager.GetString("PAListarCarreras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_Listar_DA.
        /// </summary>
        internal static string PAListarDA {
            get {
                return ResourceManager.GetString("PAListarDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_Listar_Estudiante.
        /// </summary>
        internal static string PAListarEstudiantes {
            get {
                return ResourceManager.GetString("PAListarEstudiantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_listar_grupos.
        /// </summary>
        internal static string PAListarGrupos {
            get {
                return ResourceManager.GetString("PAListarGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_listar_profesores.
        /// </summary>
        internal static string PAListarProfesores {
            get {
                return ResourceManager.GetString("PAListarProfesores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_Listar_Rol.
        /// </summary>
        internal static string PAListarRol {
            get {
                return ResourceManager.GetString("PAListarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_Listar_Usuarios.
        /// </summary>
        internal static string PAListarUsuarios {
            get {
                return ResourceManager.GetString("PAListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA_listar_Usuarios_Cedula.
        /// </summary>
        internal static string PAlistarUsuariosCedula {
            get {
                return ResourceManager.GetString("PAlistarUsuariosCedula", resourceCulture);
            }
        }
    }
}
